pass tags

diff --git a/.github/actions/tag-builder/action.yml b/.github/actions/tag-builder/action.yml
--- a/.github/actions/tag-builder/action.yml
+++ b/.github/actions/tag-builder/action.yml
@@ -17,33 +17,48 @@ runs:
       shell: bash
       id: check-tag
       run: |
+        echo "::notice:: Ensure Commit Has No Tag..."
         # Check if the current commit already has a matching version tag
         tag=$(git tag --points-at HEAD | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" || true)        
         if [ -n "$tag" ]; then
-          echo "::error:: commit already has a tag, skipping tagging."        
+          echo "::error:: commit already has a tag, skipping tagging."
+          exit 1
         fi
-        echo "tag=$tag" >> $GITHUB_OUTPUT
-        echo "::notice:: current commit has no tag, continue tagging"
+        echo "::notice:: commit ensured."
 
     - name: Find Latest Tag for Base Version
-      if: "! ${{ steps.check-tag.outputs.tag }}"
       shell: bash
-      id: get-tags
+      id: new-tag
       run: |
+        echo "::notice:: Calculate Next Tag..."
         # Find the latest tag matching the base version pattern (e.g., 4.3.*)
         latest_tag=$(git tag --list "${{ inputs.target_branch }}.*" --sort=-v:refname | head -n 1)
         
         # Determine the new tag
         if [ -z "$latest_tag" ]; then
-          echo "::notice:: latest base version tag: no latest tag"          
+          echo "::notice:: > latest base version tag: no latest tag"          
           # No existing tags, start with .1
           new_tag="${{ inputs.target_branch }}.1"
         else
-          echo "::notice:: latest base version tag: $latest_tag"          
+          echo "::notice:: > latest base version tag: $latest_tag"          
           # Increment the patch version
           patch_version=${latest_tag##*.}
           new_patch_version=$((patch_version + 1))
           new_tag="${{ inputs.target_branch }}.$new_patch_version"
         fi
-        echo "::notice:: new tag: $new_tag"          
+        echo "::notice:: next tag calculated: $new_tag"
+        echo "tag=${new_tag}" >> $GITHUB_OUTPUT
+
+    - name: Approve and Return new Tags
+      shell: bash
+      id: get-tags
+      run: |
+        echo "::notice:: Approve New Image Tag
+        new_tag="${{ steps.new-tag.outputs.tag }}"
+        if git ls-remote --exit-code --heads origin $new_tag; then
+          echo "::error:: tag $new_tag already exists as a branch"
+          exit 1
+        fi 
+        echo "::notice:: Image Tag Approved."
         echo "tags=${{ inputs.target_branch }} ${new_tag}" >> $GITHUB_OUTPUT
+
