start working on build-image-tags

diff --git a/.github/actions/build-image-tags/action.yml b/.github/actions/build-image-tags/action.yml
--- a/.github/actions/build-image-tags/action.yml
+++ b/.github/actions/build-image-tags/action.yml
@@ -34,16 +34,37 @@ runs:
         echo "::notice::Validating source and target branches..."
         if [ -n "${{ steps.source.outputs.branch }}" ] && [ -n "${{ steps.target.outputs.branch }}" ] ; then
           echo "::notice::> source and target matches version patterns"
-          if (( ${{ steps.source.outputs.major }} > ${{ steps.target.outputs.major }} )); then
-            echo "::error::> source major version is greater than target major version"
+          # source: 1.2.2 => target: 1.2.3
+          if [ -n "${{ steps.source.outputs.patch }}" ] && [ -n "${{ steps.target.outputs.patch }}" ] ; then
+            echo "::error::> source and target branches having a patch version"
             exit 1
           fi
-          if [ "${{ steps.source.outputs.major }}" == "${{ steps.target.outputs.major }}" ]; then
-            if (( ${{ steps.source.outputs.minor }} > ${{ steps.target.outputs.minor }} )); then
-              echo "::error::> source major is greater than target major version"
-              exit 1
-            fi        
-          fi 
+          # source: 1.2 => target: 1.3
+          if [ -z "${{ steps.source.outputs.patch }}" ] && [ -z "${{ steps.target.outputs.patch }}" ] && [ -n "${{ steps.source.outputs.minor }}" ] && [ -n "${{ steps.target.outputs.minor }}" ] ; then
+            echo "::error::> source and target branches have no patch version but both have a minor version"
+            exit 1
+          fi  
+          # source: 1 => target: 2
+          if [ -z "${{ steps.source.outputs.minor }}" ] && [ -z "${{ steps.target.outputs.minor }}" ] && [ -n "${{ steps.source.outputs.major }}" ] && [ -n "${{ steps.target.outputs.major }}" ] ; then
+            echo "::error::> source and target branches have no minor/patch version but both have a major version"
+            exit 1
+          fi         
+          # source: 1.2.3 => target: 1.1
+          if [ -n "${{ steps.source.outputs.minor }}" ] && [ -n "${{ steps.target.outputs.minor }}" ] && (( ${{ steps.source.outputs.minor }} > ${{ steps.target.outputs.minor }} )); then
+            echo "::error::> source minor version is greater than target minor version"
+            exit 1        
+          fi
+          # source: 2.2.3 => target: 1.1
+          if [ -n "${{ steps.source.outputs.major }}" ] && [ -n "${{ steps.target.outputs.major }}" ] && (( ${{ steps.source.outputs.major }} > ${{ steps.target.outputs.major }} )); then
+             echo "::error::> source major version is greater than target major version"
+             exit 1
+          fi               
+          # target: 1.2.3
+          if [ -n "${{ steps.target.outputs.patch }}" ]; then
+            echo "::error::> target branch already has a patch version"
+            exit 1
+          fi
+          # source: 1.2.2 => target: 1.2 (1.2.1 exists)
           if [ -n "${{ steps.target.outputs.minor }}" ] && [ -z "${{ steps.source.outputs.minor }}" ]; then
             pattern="${{ steps.target.outputs.prefix }}${{ steps.target.outputs.major }}"
             if [ -n "${{ steps.target.outputs.minor }}" ]; then
