refactor

diff --git a/.github/workflows/build-docker-image.yml b/.github/workflows/build-docker-image.yml
--- a/.github/workflows/build-docker-image.yml
+++ b/.github/workflows/build-docker-image.yml
@@ -6,7 +6,7 @@ on:
       image:
         description: "image name"
         type: string
-        required: true
+        required: false
       target:
         description: "build --target"
         type: string
@@ -14,7 +14,8 @@ on:
       context:
         description: "build context"
         type: string
-        required: true
+        required: false
+        default: "."
       options:
         description: "additional build options"
         type: string
@@ -35,19 +36,47 @@ jobs:
       - name: Check Out Repository
         uses: actions/checkout@v4
 
+      - name: "Prepare Build Arguments"
+        id: arguments
+        run: |
+          echo "::notice:: Preparing Build Arguments..."
+          
+          if [ -n "${{ env.IMAGE }}" ]; then
+            echo ":: > image from env: ${{ env.IMAGE }}"
+            image="${{ env.IMAGE }}"
+          elif [ -n "${{ inputs.image }}" ]; then
+            echo ":: > image from inputs: ${{ inputs.image }}"
+            image="${{ inputs.image }}"
+          else
+            echo "::error:: image ENV or inputs missing"
+            exit 1
+          fi
+          
+          if [ -n "${{ env.IMAGE }}" ]; then
+            echo "::notice:: > artifact from env: ${{ env.ARTIFACT }}"
+            artifact="${{ env.ARTIFACT }}"
+          elif [ -n "${{ inputs.artifact }}" ]; then
+          echo "::notice:: > artifact from inputs: ${{ inputs.artifact }}"
+            artifact="${{ inputs.artifact }}"
+          fi
+          
+          echo "::notice:: Build arguments prepared."
+          echo "image=$image" >> $GITHUB_OUTPUT
+          echo "artifact=$artifact" >> $GITHUB_OUTPUT
+
       - name: "Build Docker Image"
         id: build-image
         uses: ./github/actions/image-build@main
         with:
-          image: ${{ inputs.image }}
+          image: ${{ steps.arguments.outputs.image }}
           target: ${{ inputs.target }}
           context: ${{ inputs.context }}
           options: ${{ inputs.options }}
           build_args_file: ${{ inputs.build_args_file }}
 
       - name: "Save Docker Image"
-        if: ${{ inputs.artifact }}
+        if: ${{ steps.arguments.outputs.artifact }}
         uses: ./github/actions/image-save@main
         with:
-          image: ${{ inputs.image }}
-          artifact: ${{ inputs.artifact }}
+          image: ${{ steps.arguments.outputs.image }}
+          artifact: ${{ steps.arguments.outputs.artifact }}
