Update build-workflow.yml
start from scratch, step by step

diff --git a/.github/workflows/build-workflow.yml b/.github/workflows/build-workflow.yml
--- a/.github/workflows/build-workflow.yml
+++ b/.github/workflows/build-workflow.yml
@@ -41,113 +41,30 @@ on:
         required: true
 
 jobs:
-  checkout:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out kernel.deployment repository
-        uses: actions/checkout@v4
-        with:
-          repository: draftm0de/kernel.deployment
-          path: parent
-
-      - name: Check out own (parent) repository
-        uses: actions/checkout@v4
-        with:
-          path: content
-
-      - name: Archive content and parent directories
-        run: |
-          tar -czf source.tar.gz content/ parent/
-
-
-      - name: Upload archive as artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: source
-          path: source.tar.gz
-
   build:
-    needs: checkout
     runs-on: ubuntu-latest
     steps:
-      - name: Download the artifact with the checked-out repositories
-        uses: actions/download-artifact@v3
-        with:
-          name: source
+      - name: Check Uut Own (parent) Repository
+        uses: actions/checkout@v4
 
       - name: Build Docker Image
         env:
           BUILD_ARGS_FILE: ${{ inputs.build_args_file }}
         run: |
-          echo "[Notice] Build image..."
-          CONTEXT="content/${{ inputs.context }}"
-          ls $CONTEXT -la
-          IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:latest"
-          BUILD_ARGS_FILE="$CONTEXT/${BUILD_ARGS_FILE:-.build_args}"
-          ls $CONTEXT -la
-          if [ -f "$BUILD_ARGS_FILE" ]; then
-            ./parent/docker.sh build --tag $IMAGE --build-args=$BUILD_ARGS_FILE $CONTEXT
+          echo "::Notice:: Build image..."
+          if [ -d "${{ inputs.context }}" ]; then
+            IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:latest"
+            if [ -f "$BUILD_ARGS_FILE" ]; then
+              echo "::notice::- Build with --build-args"
+              BUILD_ARGS=$(cat "$BUILD_ARG_FILE" | awk -F "=" '{ print "--build-arg " $1"="$2;}' | xargs)
+              docker build --tag $IMAGE $BUILD_ARGS ${{ inputs.context }}
+            else
+              docker build --tag $IMAGE ${{ inputs.context }}
+            fi
           else
-            docker build --tag $IMAGE $CONTEXT
+            echo "::error:: Directory ${{ inputs.context }} does not exist"
+            exit 1
           fi
-          echo "[Notice] > build successfully"
-
-      - name: Log in to Docker Hub
-        run: |
-          echo "${{ secrets.docker_password }}" > DOCKER_PASSWORD
-          cat "DOCKER_PASSWORD" | docker login -u "${{ secrets.docker_username }}" --password-stdin   
-
-      - name: Protect duplicate SHA
-        run: |
-          echo "[Notice] Protect built SHA against remote"          
-          REPOSITORY="${{ inputs.namespace }}/${{ inputs.image }}"
-          IMAGE="$REPOSITORY:${{ inputs.protected_tag }}"
-          SHA=$("./parent/docker.sh" "image sha" "$IMAGE")
-          echo "[Debug] SHA for $IMAGE: $SHA"
-          ("./parent/docker.sh" "image tags" "$REPOSITORY" "--remote" "--sha=$SHA" "--exists")
-          echo "[Notice] > Protection successfully"
-  tag:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Get Latest Remote Tag
-        id: get_latest_tag
-        run: |
-          IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:latest"
-          echo "[Notice] Get latest remote tag for $IMAGE"
-          LATEST_TAG=$("./parent/docker.sh" "image tags" "$IMAGE" "--remote" "--latest=patch")
-          echo "LATEST_TAG=${LATEST_TAG:-0.0.0}" >> $GITHUB_ENV
-          echo "[Notice] > latest remote tag for $IMAGE: $LATEST_TAG"          
-
-      - name: Tag Docker Image
-        run: |
-          echo "[Notice] Tag docker image"
-          REPOSITORY="${{ inputs.namespace }}/${{ inputs.image }}"          
-          IMAGE="$REPOSITORY:latest"
-          CONTEXT="content/${{ inputs.context }}"
-          TAG_VERSION_FILE="$CONTEXT/.version"
-          if [ -f "$TAG_VERSION_FILE" ]; then
-            TAG_VERSION=$(cat $TAG_VERSION_FILE)
-            TAG_INCREASE="--tag-increase=$TAG_VERSION"
-            echo "[Notice] automatically increase: $TAG_VERSION"
-          else
-            TAG_INCREASE="--tag-increase"
-          fi         
-          echo "[Notice] latest tag: $LATEST_TAG"
-          echo "[Notice] count of levels for tagging: ${{ inputs.tag_level }}"
-          TAGS=$("./parent/docker.sh" "image tag" "$IMAGE" "${REPOSITORY}:${LATEST_TAG}" "$TAG_INCREASE" "--tag-level=${{ inputs.tag_level }}")
-          TAGS_COMPRESSED=$(echo "$TAGS" | tr '\n' ' ')
-          echo "TAGS=$TAGS_COMPRESSED" >> $GITHUB_ENV     
-          echo "[Notice] > docker image tagged successfully"          
-
-      - name: Push Docker Image
-        run: |
-          BUILT_IMAGE_NAME="${{ inputs.namespace }}/${{ inputs.image }}:${{ inputs.tag }}"
-          echo "[Notice] Push docker images"
-          TAGS=($TAGS)
-          TAGS+=("$BUILT_IMAGE_NAME")
-          for TAG in "${TAGS[@]}"; do
-            echo "docker push $TAG"
-          done
-          echo "[Notice] > Pushing docker images successfully"         
+          echo "::notice:: > build successfully"
+       
           
