refactor

diff --git a/.github/workflows/scan-docker-image.yml b/.github/workflows/scan-docker-image.yml
--- a/.github/workflows/scan-docker-image.yml
+++ b/.github/workflows/scan-docker-image.yml
@@ -49,8 +49,24 @@ jobs:
             $image = "${{ inputs.image }}"
           fi
           
+          if [[ "${{ inputs.image }}" == */* ]]; then
+            image="${{ inputs.image }}"
+            namespace="${image%%/*}"
+            echo "::notice:: > namespace: $namespace"
+          else
+            echo "::error:: cannot extract any namespace from inputs.image"
+            exit 1
+          fi         
+          
           echo "::notice:: Scan arguments prepared."
           echo "image=$image" >> $GITHUB_OUTPUT
+          echo "namespace=$namespace" >> $GITHUB_OUTPUT
+
+      - name: "Login to Docker Hub"
+        uses: docker/login-action@v3
+        with:
+          username: ${{ steps.arguments.outputs.namespace }}
+          password: ${{ secrets.docker_token }}
 
       - name: "Scan Docker Image"
         uses: docker/scout-action@v1
