update business logic to - get tags - increase

diff --git a/.github/workflows/sha-protection.yml b/.github/workflows/sha-protection.yml
--- a/.github/workflows/sha-protection.yml
+++ b/.github/workflows/sha-protection.yml
@@ -7,10 +7,10 @@ on:
         description: "docker image (name / artifact.file)"
         required: true
         type: string    
-      artifact_name:
+      artifact:
         description: "artifact name"
         required: false
-        type: string  
+        type: string
     secrets:
       docker_username:
         required: true
@@ -22,6 +22,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       ARTIFACT_PATH: "./artifacts"
+      IMAGE: ${{ inputs.image }}
     steps: 
       - name: Check Out Repository
         uses: actions/checkout@v4
@@ -29,19 +30,18 @@ jobs:
           repository: draftm0de/kernel.deployment
 
       - name: Download the Docker Image From Artifacts
-        if: ${{ inputs.artifact_name }}
+        if: ${{ inputs.artifact }}
         uses: actions/download-artifact@v4
         with:
-          name: ${{ inputs.artifact_name }}
+          name: ${{ inputs.artifact }}
           path: ${{ env.ARTIFACT_PATH }}      
 
       - name: Load Docker Image from Artifact
-        if: ${{ inputs.artifact_name }}
-        id: load-image
+        if: ${{ inputs.artifact }}
         run: |
           echo "::notice:: Load Docker Image..."
           
-          INPUT="${{ env.ARTIFACT_PATH }}/${{ inputs.image }}.tar"
+          INPUT="${{ env.ARTIFACT_PATH }}/${{ env.image }}.tar"
           echo "::notice:: > load from: ${INPUT}"
           
           IMAGE=$(docker load --input ${INPUT} | grep 'Loaded image' | awk '{print $3}')
@@ -51,18 +51,29 @@ jobs:
           echo "::notice:: > load image successfully"
 
       - name: Get Local Image SHA
+        id: local-sha
         run: |
           echo "::notice:: Get Local SHA..."
           
           SHA=$(./docker.sh image sha ${{ env.image }})
           echo "::notice:: > SHA for ${{ env.image }}: $SHA"
-          echo "local_sha=${SHA}" >> $GITHUB_ENV
-          
-          echo "::notice:: > Get Local SHA successfully"
+          echo "sha=${SHA}" >> $GITHUB_OUTPUT
+          if [ -z "${SHA}" ]; then
+            echo "::error:: > Get Local SHA failure"
+            exit 1
+          else 
+            echo "::notice:: > Get Local SHA successfully"
+          fi
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.docker_username }}
-          password: ${{ secrets.docker_password }}   
-      
+          password: ${{ secrets.docker_password }}
+
+      - name: Get Remote Tags
+        run: |
+          echo "::notice:: Get Remote Tags..."
+          
+          TAGS=$(./docker.sh image tags ${{ env.image }} --sha=${{ steps.local-sha.outputs.sha }})
+          echo "::notice:: > TAGS for ${{ env.image }}: $TAGS"             
